// import MapUseWithReact from "@/components/v-10-with-react";
// import MapLocatorStore from "@/components/v-11-store-locator";
// import MapSortStoresDistance from "@/components/v-12-store-locator-sort";
// import MapOptimizationAPI from "@/components/v-13-Optimization-API";
// import MapChangesOverTime from "@/components/v-14-NYC OpenData";
import MapMeasureDistance from "@/components/v-15-turf-distance";
import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Using Mapbox GL JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <MapView /> */}
      {/* <MapViewGecoder /> */}
      {/* <MapCustomMarkers /> */}
      {/* <MapDirectionsAPI /> */}
      {/* <MapMatchingAPI /> */}
      {/* <DrawPolygonCalculate /> */}
      {/* <MapTurfAnalysis /> */}
      {/* <MapHoverEarthquake /> */}
      {/* <MapTimezoneFinder />*/}
      {/* <MapElevationFinder /> */}
      {/* <MapFoodFinder /> */}
      {/* <MapUseWithReact /> */}
      {/* <MapLocatorStore /> */}
      {/* <MapSortStoresDistance /> */}
      {/* <MapOptimizationAPI /> */}
      {/* <MapChangesOverTime /> */}
      <MapMeasureDistance />
    </>
  );
};

export default HomePage;
